import type { ServiceRecord } from "./types";

export const services: ServiceRecord[] = [
  {
    slug: "domestic-cleaning",
    name: "Domestic cleaning in York",
    shortName: "Domestic cleaning",
    metaDescription: "Regular and one-off domestic cleaning for homes across York and the wider YO postcode area. Tell Sunshine Cleaning what would help and request a quote.",
    updated: "2026-08-31",
    eyebrow: "A dependable helping hand",
    summary: "Regular, practical cleaning shaped around your home and weekly rhythm.",
    description: "Keep the everyday jobs under control with a clear, agreed cleaning plan. We focus on the rooms and details that matter most to your household, whether you need regular support or a one-off refresh.",
    image: "domestic-hero",
    imageAlt: "Cleaner wiping a wooden worktop in a lived-in York kitchen",
    icon: "home",
    benefits: ["A plan based on your priorities", "Flexible regular or one-off visits", "Clear communication before the clean"],
    inclusions: ["Kitchen surfaces and cupboard fronts", "Bathroom fixtures and mirrors", "Dusting reachable surfaces", "Vacuuming and mopping", "Bedroom and living-space reset", "Bins emptied as agreed"],
    suitableFor: ["Busy households", "Regular home upkeep", "Pre- or post-guest refreshes"],
    faqs: [
      { question: "Can I choose the rooms you focus on?", answer: "Yes. Tell us what would help most and we will agree priorities before the visit." },
      { question: "Do you offer weekly and fortnightly cleaning?", answer: "You can request the frequency that suits you. Availability is confirmed with your quote." },
      { question: "Do I need to be at home?", answer: "Not necessarily. Access arrangements can be agreed privately before the clean." },
    ],
  },
  {
    slug: "deep-cleaning",
    name: "Deep cleaning in York",
    shortName: "Deep cleaning",
    metaDescription: "Detailed deep cleaning for York homes and properties across the wider YO postcode area. Agree the rooms, priorities and scope before requesting a quote.",
    updated: "2026-08-31",
    eyebrow: "A thorough reset",
    summary: "More time for the build-up and overlooked details that routine cleaning cannot reach.",
    description: "A deep clean works methodically through your chosen rooms, giving extra attention to grease, limescale, edges, fittings and areas that are easy to miss during a normal weekly clean.",
    image: "deep-cleaning",
    imageAlt: "Gloved hands carefully cleaning taps and tile grout in a bathroom",
    icon: "sparkle",
    benefits: ["Room-by-room scope agreed first", "Detail-led cleaning", "Useful before occasions or seasonal resets"],
    inclusions: ["Detailed kitchen and bathroom cleaning", "Limescale and soap-residue attention", "Skirting boards, ledges and reachable frames", "Cupboard fronts and external appliance surfaces", "Detailed vacuuming and floor cleaning", "High-touch points and fittings"],
    suitableFor: ["Seasonal cleaning", "Homes needing a fresh start", "Before or after hosting"],
    faqs: [
      { question: "What is the difference between a standard and deep clean?", answer: "A deep clean allows more time for detail, build-up and areas that are not normally included in routine upkeep." },
      { question: "Can the clean focus on only part of my home?", answer: "Yes. A focused kitchen, bathroom or selected-room deep clean may be more useful than a whole-property clean." },
      { question: "How long will it take?", answer: "That depends on the size, condition and agreed scope. We will ask for the details needed to quote sensibly." },
    ],
    relatedGuide: "what-is-included-in-a-deep-clean",
  },
  {
    slug: "end-of-tenancy-cleaning",
    name: "End-of-tenancy cleaning in York",
    shortName: "End-of-tenancy cleaning",
    metaDescription: "End-of-tenancy cleaning for York tenants, landlords and property managers, available across the wider YO postcode area. Request a clear quote.",
    updated: "2026-08-31",
    eyebrow: "Ready for the next chapter",
    summary: "A structured clean for tenants, landlords and property managers between occupancies.",
    description: "Moving dates are demanding enough. We work from an agreed property-wide scope, concentrating on the practical details that help a home feel properly reset before handover or a new tenancy.",
    image: "end-of-tenancy",
    imageAlt: "Cleaner vacuuming an empty British rental room beside moving boxes",
    icon: "keys",
    benefits: ["Clear property-wide checklist", "Suitable for empty or nearly empty homes", "Easy coordination around handover dates"],
    inclusions: ["Kitchen units and external appliances", "Bathroom fixtures, tiles and mirrors", "All reachable surfaces and woodwork", "Inside empty cupboards when agreed", "Vacuuming and floor cleaning", "Final visual check against the scope"],
    suitableFor: ["Outgoing tenants", "Landlords", "Letting and property managers"],
    faqs: [
      { question: "Does cleaning guarantee my deposit?", answer: "No cleaner can guarantee a deposit decision. We can agree a thorough scope, while the final decision remains with the landlord or agent." },
      { question: "Can you clean an empty property?", answer: "Yes. Empty properties are often easier to assess and clean thoroughly." },
      { question: "Should I share my inventory or check-out notes?", answer: "Yes. Relevant notes help us understand any specific cleaning points before we confirm the work." },
    ],
    relatedGuide: "end-of-tenancy-cleaning-checklist",
  },
  {
    slug: "holiday-let-cleaning",
    name: "Holiday-let cleaning in York",
    shortName: "Holiday-let cleaning",
    metaDescription: "Holiday-let and short-stay changeover cleaning in York and across the wider YO postcode area, shaped around your property checklist. Request a quote.",
    updated: "2026-08-31",
    eyebrow: "Between one welcome and the next",
    summary: "Careful changeovers for York holiday lets, guest houses and short-stay properties.",
    description: "A successful turnover is a sequence, not just a clean. We can work from your property checklist to prepare key guest areas, reset presentation and report anything that needs your attention.",
    image: "holiday-let",
    imageAlt: "Cleaner making a bed in a characterful York townhouse bedroom",
    icon: "bed",
    benefits: ["Checklist-led turnovers", "Guest-ready presentation", "Practical issue reporting"],
    inclusions: ["Bathroom and kitchen reset", "Vacuuming and floor cleaning", "Bed presentation with supplied linen", "High-touch surfaces", "Bins and visible consumable check", "Final room-by-room presentation check"],
    suitableFor: ["Holiday lets", "Serviced accommodation", "Short-stay properties"],
    faqs: [
      { question: "Can you work from our existing turnover checklist?", answer: "Yes. A property-specific checklist is the best way to keep every changeover consistent." },
      { question: "Do you provide linen?", answer: "Please tell us about your linen arrangements when enquiring. We do not claim a linen-hire service unless specifically agreed." },
      { question: "Can you report damage or low supplies?", answer: "We can agree a simple reporting routine for visible issues and selected consumables." },
    ],
    relatedGuide: "york-holiday-let-turnover-checklist",
  },
  {
    slug: "office-commercial-cleaning",
    name: "Office and commercial cleaning in York",
    shortName: "Office & commercial",
    metaDescription: "Office and small commercial cleaning in York and the wider YO postcode area, with a practical scope shaped around your premises. Request a quote.",
    updated: "2026-08-31",
    eyebrow: "A better start to the working day",
    summary: "Straightforward cleaning plans for offices and small commercial spaces across York.",
    description: "Every workplace runs differently. We agree the priority areas, access and preferred frequency first, then shape a practical routine around your team and premises.",
    image: "office-commercial",
    imageAlt: "Cleaner wiping a glass partition in a small York office",
    icon: "office",
    benefits: ["Cleaning shaped around your premises", "Flexible scheduling requests", "Clear list of agreed tasks"],
    inclusions: ["Desks and shared surfaces as agreed", "Kitchen and washroom areas", "Interior glass spot cleaning", "Vacuuming and hard floors", "Bins and recycling points", "Entrances and high-touch points"],
    suitableFor: ["Small offices", "Studios and shared workspaces", "Selected commercial premises"],
    faqs: [
      { question: "Can cleaning take place outside office hours?", answer: "Tell us your preferred access window and we will confirm what is available." },
      { question: "Can we set different frequencies for different areas?", answer: "Yes. High-use areas can be prioritised more frequently than low-use rooms." },
      { question: "Do you offer a site visit?", answer: "For premises that need a closer look, we can arrange the most appropriate next step after your enquiry." },
    ],
    relatedGuide: "how-often-should-an-office-be-cleaned",
  },
  {
    slug: "after-builders-cleaning",
    name: "After-builders cleaning in York",
    shortName: "After-builders cleaning",
    metaDescription: "After-builders cleaning for completed renovation work in York and the wider YO postcode area. Agree the dust-removal scope and request a quote.",
    updated: "2026-08-31",
    eyebrow: "From finished work to finished room",
    summary: "Careful removal of settled dust and residue after renovation or building work.",
    description: "Once the trades have finished and the area is safe, an after-builders clean helps reveal the completed space. We focus on settled fine dust, reachable surfaces, floors, frames and fittings within an agreed scope.",
    image: "after-builders",
    imageAlt: "Cleaner removing fine building dust from a new timber window frame",
    icon: "brush",
    benefits: ["Detailed scope based on the completed work", "Attention to settled fine dust", "A careful final-room reset"],
    inclusions: ["Dust removal from reachable surfaces", "Frames, ledges and skirting boards", "External surfaces of fitted units", "Vacuuming with suitable equipment", "Floor cleaning where appropriate", "Final pass over key fittings"],
    suitableFor: ["Renovated rooms", "Extensions and refurbishments", "Post-trade handovers"],
    faqs: [
      { question: "When should the clean be booked?", answer: "The space should be safe, ventilated and free of ongoing dusty work before the clean starts." },
      { question: "Do you remove building waste?", answer: "No waste-removal service is implied. Rubble and trade waste should be removed before cleaning unless separately agreed." },
      { question: "Can all dust be removed in one visit?", answer: "Fine dust can continue settling. We will explain what is realistic for the condition and scope of the property." },
    ],
  },
];

export const serviceBySlug = new Map(services.map((service) => [service.slug, service]));
